# Generated by Django 5.0.6 on 2024-05-23 11:19

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_grouprecord_event_date_alter_socialgroup_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprecord',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='socialgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=social.models.user_group_logo_path),
        ),
    ]
