# Generated by Django 5.0.6 on 2024-05-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='grouprecord',
            options={'ordering': ['created_date']},
        ),
    ]
