# Generated by Django 5.0.6 on 2024-05-23 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_comment_options_alter_grouprecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprecord',
            name='group',
            field=models.ForeignKey(default='256ecc852a4141a2bdef96782bd79248', on_delete=django.db.models.deletion.CASCADE, related_name='record_parent', to='social.socialgroup'),
            preserve_default=False,
        ),
    ]
